### ISSUE TITLE
TestNewAgentClientWithYamux unit test timing out

### ISSUE THREAD

**Issue by chavafg** [kata-containers/agent#307]
I have seen this lately:

```
11:31:24 INFO: Running 'go test' as root user on package 'github.com/kata-containers/agent/protocols/client' with flags '-v -race -timeout 10s'
11:31:25 === RUN   TestNewAgentClient
11:31:26 --- PASS: TestNewAgentClient (1.01s)
11:31:26 === RUN   TestNewAgentClientWithYamux
11:31:35 coverage: 79.2% of statements
11:31:35 panic: test timed out after 10s
11:31:35 
11:31:35 goroutine 10 [running]:
11:31:35 testing.(*M).startAlarm.func1()
11:31:35 	/usr/local/go/src/testing/testing.go:1240 +0x146
11:31:35 created by time.goFunc
11:31:35 	/usr/local/go/src/time/sleep.go:172 +0x52
```

From: 
http://jenkins.katacontainers.io/job/kata-containers-agent-centos-7-4-master/17/console
http://jenkins.katacontainers.io/job/kata-containers-agent-centos-7-4-master/19/console

**Comment by bergwolf** [comment]
Hit another at 
http://jenkins.katacontainers.io/job/kata-containers-agent-fedora-27-PR/205/console
```
=== RUN   TestNewAgentClientWithYamux
coverage: 81.9% of statements
panic: test timed out after 10s

goroutine 79 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0x146
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4201c0000, 0xca1582, 0x1b, 0xcbd150, 0xc42006fc01)
	/usr/local/go/src/testing/testing.go:825 +0x597
testing.runTests.func1(0xc4201c0000)
	/usr/local/go/src/testing/testing.go:1063 +0xa5
testing.tRunner(0xc4201c0000, 0xc42006fd48)
	/usr/local/go/src/testing/testing.go:777 +0x16e
testing.runTests(0xc4201924a0, 0x1054260, 0x2, 0x2, 0xc4201be000)
	/usr/local/go/src/testing/testing.go:1061 +0x4e2
testing.(*M).Run(0xc4201be000, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x2ce
main.main()
	_testmain.go:90 +0x325

goroutine 23 [chan receive]:
github.com/kata-containers/agent/protocols/client.TestNewAgentClientWithYamux(0xc4201c01e0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client_test.go:155 +0x31a
testing.tRunner(0xc4201c01e0, 0xcbd150)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565

goroutine 24 [runnable]:
time.startTimer(0xc420598468)
	/usr/local/go/src/runtime/time.go:111 +0x39
time.NewTimer(0x3b9aca00, 0xca474b)
	/usr/local/go/src/time/sleep.go:95 +0x130
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*Server).Serve(0xc420001e00, 0xd1d200, 0xc4201f4000, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/server.go:511 +0x3d8
github.com/kata-containers/agent/protocols/client.startMockServer.func1(0xc4202b6000, 0xd1d680, 0xc4200a2d20, 0x1, 0xc4201c01e0, 0xc420001e00)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client_test.go:55 +0x9a
created by github.com/kata-containers/agent/protocols/client.startMockServer
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client_test.go:44 +0x23a

goroutine 58 [chan receive]:
github.com/kata-containers/agent/protocols/client.commonDialer(0x4a8169789, 0xc4201a4140, 0xd15dc0, 0xc4201b8ba0, 0x2, 0x2, 0xd15dc0, 0xc4201b8ba0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:284 +0x127
github.com/kata-containers/agent/protocols/client.vsockDialer(0xc4204a2100, 0xb, 0x4a8169789, 0x4a817a687, 0xc4200ba780, 0xc4200ae7d0, 0x477908)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:305 +0x2d8
github.com/kata-containers/agent/protocols/client.agentDialer.func1(0xc4204a2100, 0xb, 0x4a8169789, 0x0, 0x0, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:185 +0xb4
github.com/kata-containers/agent/vendor/google.golang.org/grpc.WithDialer.func1.1(0xd1e240, 0xc4200ba780, 0xc4204a2100, 0xb, 0xc4201c6050, 0x30, 0xc4201c6080, 0xc42022b540)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:293 +0xfe
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.dial(0xd1e240, 0xc4200ba780, 0xc4200602b0, 0xc4204a2100, 0xb, 0xc4202ac110, 0xc4202a2420, 0xc4202b6780, 0xc4200aa1b0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/http2_client.go:112 +0x78
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.newHTTP2Client(0xd1e1c0, 0xc4200b09c0, 0xc4204a2100, 0xb, 0x0, 0x0, 0xc4204a2100, 0xb, 0xc9927e, 0xd, ...)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/http2_client.go:161 +0x159
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.NewClientTransport(0xd1e1c0, 0xc4201f8400, 0xc4204a2100, 0xb, 0x0, 0x0, 0xc4204a2100, 0xb, 0xc9927e, 0xd, ...)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/transport.go:510 +0xbe
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc42021c200, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:965 +0x4f5
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc42021c200)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:739 +0x3d
created by github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).connect
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:738 +0x173

goroutine 10 [runnable]:
github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock.dialStream(0x6400000000, 0x0, 0x0, 0xd171a0, 0x1016690)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock/conn_linux.go:47 +0xbe
github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock.Dial(0x6400000000, 0x1, 0xb9bf8, 0xd171a0, 0xc4201eaf60)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock/vsock.go:49 +0x43
github.com/kata-containers/agent/protocols/client.vsockDialer.func1(0x102a490, 0xc400000001, 0xb9bfb, 0x1016690)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:300 +0x73
github.com/kata-containers/agent/protocols/client.commonDialer.func1(0xc420036360, 0xc4200241f0, 0xc4201c6460, 0xc4200363c0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:267 +0xbd
created by github.com/kata-containers/agent/protocols/client.commonDialer
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:258 +0xe6

goroutine 59 [runnable]:
github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock.dialStream(0x6400000000, 0x0, 0x0, 0xd171a0, 0x1016690)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock/conn_linux.go:47 +0xbe
github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock.Dial(0x6400000000, 0x1, 0xb9bfd, 0xd171a0, 0xc4201ebf60)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock/vsock.go:49 +0x43
github.com/kata-containers/agent/protocols/client.vsockDialer.func1(0x102a490, 0xc400000001, 0xb9c00, 0x1016690)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:300 +0x73
github.com/kata-containers/agent/protocols/client.commonDialer.func1(0xc4200367e0, 0xc4201a4140, 0xc4200ae820, 0xc420036840)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:267 +0xbd
created by github.com/kata-containers/agent/protocols/client.commonDialer
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:258 +0xe6

goroutine 70 [chan receive]:
github.com/kata-containers/agent/protocols/client.commonDialer(0x4a817264d, 0xc4200241f0, 0xd15dc0, 0xc4201c85d0, 0x2, 0x2, 0xd15dc0, 0xc4201c85d0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:284 +0x127
github.com/kata-containers/agent/protocols/client.vsockDialer(0xc4202a80a0, 0xb, 0x4a817264d, 0xbedc590b6d63eecf, 0x1737dd4, 0x1065780, 0x4a817264d)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:305 +0x2d8
github.com/kata-containers/agent/vendor/google.golang.org/grpc.WithDialer.func1.1(0xd1e240, 0xc4200866c0, 0xc4202a80a0, 0xb, 0xc420208370, 0x30, 0xc4202083a0, 0xc4202db540)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:293 +0xfe
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.dial(0xd1e240, 0xc4200866c0, 0xc4202ac190, 0xc4202a80a0, 0xb, 0xc420060160, 0x160, 0xc4202c0000, 0xc4201f0638)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/http2_client.go:112 +0x78
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.newHTTP2Client(0xd1e1c0, 0xc42001e3c0, 0xc4202a80a0, 0xb, 0x0, 0x0, 0xc4202a80a0, 0xb, 0xc9927e, 0xd, ...)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/http2_client.go:161 +0x159
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.NewClientTransport(0xd1e1c0, 0xc4202a6100, 0xc4202a80a0, 0xb, 0x0, 0x0, 0xc4202a80a0, 0xb, 0xc9927e, 0xd, ...)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/transport.go:510 +0xbe
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc4202e2000, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:965 +0x4f5
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc4202e2000)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:739 +0x3d
created by github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).connect
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:738 +0x173
FAIL	github.com/kata-containers/agent/protocols/client	10.029s
make: *** [Makefile:64: test] Error 1
Build step 'Execute shell' marked build as failure
```

**Comment by bergwolf** [comment]
The problem turns out to be that closing errors are treated at temporary errors and grpc listener will just sleep a bit and retry again. 

https://github.com/grpc/grpc-go/blob/5fe10fccafd3e35e84837ecc5a66e0f9600ab64e/internal/transport/transport.go#L659

That is fixed in the latest grpc code where the `serve()` function waits on a channel that is closed by `server.Stop()`. I'll update grpc vendor for it.
